# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

FASTLANE_APPLE_USER = ENV['FASTLANE_APPLE_USER']
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']

default_platform(:ios)

platform :ios do
  desc "Deploy Production to Testflight"
  lane :deploy_production_to_testflight do
    build_app
    upload_to_testflight(
      skip_waiting_for_build_processing: true, 
      app_identifier: 'template.app'
    )
  end
end

platform :ios do
  desc "Deploy PreProduction to Testflight"
  lane :deploy_preproduction_to_testflight do
    build_app
    upload_to_testflight(
      skip_waiting_for_build_processing: true, 
      app_identifier: 'template.app.preprod'
    )
  end
end

platform :ios do
  desc "Deploy Staging to Testflight"
  lane :deploy_staging_to_testflight do
    build_app
    upload_to_testflight(
      skip_waiting_for_build_processing: true, 
      app_identifier: 'template.app.stg'
    )
  end
end
